[하예준] : Request merge on main from feature/invest-summary
wecode-bootcamp-korea/24-2nd-111percent-backend pull request #11
Opened 2021-09-28 17:34 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 나의 투자 상품 정보 Get 함수 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-28 17:35 UTC, TedJunny commented
URL : https://aquerytool.com/aquerymain/index/?rurl=ce9cc1cf-b99c-47c0-9176-395ff63b8f77&
Password : 3z1m54

2021-09-29 02:08 UTC, lordmyshepherd requested changes

2021-09-29 02:08 UTC, lordmyshepherd commented on transactions/models.py
> +    repayment_state = models.ForeignKey(RepaymentState, on_delete=models.PROTECT)
convention 맞춰주세요~

2021-09-29 02:08 UTC, lordmyshepherd commented on transactions/tests.py
> +        InvestmentState.objects.create(id=3, name="손실")
테스트를 작성하실 때도 테스트 실행 속도를 고려해서 작성해야 합니다.
그러므로 `bulk_create`를 사용해서 데이터를 넣어주세요.

2021-09-29 02:08 UTC, lordmyshepherd commented on transactions/tests.py
> +        RepaymentState.objects.create(id=3, name="연체")
마찬가지 입니다.

2021-09-29 02:08 UTC, lordmyshepherd commented on transactions/tests.py
> +        self.assertEqual(response.status_code, 200)
`status code`만 비교하지 말고 결과값 전체를 비교해주세요.

2021-09-29 02:08 UTC, lordmyshepherd commented on transactions/views.py
> +                },
이부분은 아래와 같이 줄여볼 수 있을까요?

```suggestion
                "grade": {
                    "A": portfolios.filter(investment__grade__name__contains="A")).aggregate(amounts=Sum("amounts"))["amounts"],
                    "B":portfolios.filter(investment__grade__name__contains="B")).aggregate(amounts=Sum("amounts"))["amounts"],
                    ..
                },
```

2021-09-29 02:08 UTC, lordmyshepherd commented on transactions/views.py
> +class PortfolioView(View):
어려운 기능을 잘 구현해주셨네요! 고생 많으셨습니다! 👍

2021-09-29 02:08 UTC, lordmyshepherd commented on transactions/views.py
> +        return JsonResponse({"results": results}, status=200)
예준님 다음에 리펙토링을 위해서 코멘트 남겨 놓습니다! (지금 반영하지 말고 프로젝트 끝나고 반영해보세요!)

지금은 매번 `aggregate()` 하기에 database에 많은 요청을 보내고 있는 것 같아 보입니다. 아래와 같이 annotate + filter 조합을 사용해서 리펙토링 해보세요~

```suggestion
        user = User.objects.annotate(
            total_amounts_of_grade_a = Sum("protfoilos__amounts", filter=Q(investment__grade__name__contains="A")),
            total_amounts_of_grade_b = Sum("protfoilos__amounts", filter=Q(investment__grade__name__contains="B")),
            ..
        ).get(id = request.user.id)
```

2021-09-29 03:42 UTC, TedJunny commented on transactions/tests.py
> +        RepaymentState.objects.create(id=3, name="연체")
수정했습니다

2021-09-29 03:42 UTC, TedJunny commented on transactions/tests.py
> +        InvestmentState.objects.create(id=3, name="손실")
수정했습니다

2021-09-29 03:44 UTC, TedJunny commented on transactions/views.py
> +class PortfolioView(View):
감사합니다!

2021-09-29 03:45 UTC, TedJunny commented on transactions/models.py
> +    repayment_state = models.ForeignKey(RepaymentState, on_delete=models.PROTECT)
수정했습니다!

2021-09-29 04:44 UTC, TedJunny commented on transactions/views.py
> +                },
수정했습니다!

2021-09-29 05:03 UTC, TedJunny commented on transactions/tests.py
> +        self.assertEqual(response.status_code, 200)
수정했습니다!

2021-09-29 06:26 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-29 06:26 UTC, merged