[하예준] Request merge on main from feature/transaction-post
wecode-bootcamp-korea/24-2nd-111percent-backend pull request #8
Opened 2021-09-16 14:38 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 투자 Post Method 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 상품 투자 시에 거래 데이터 객체 생성
- 예치금 계좌의 잔액을 차감해서 저장
- 상품 모집 금액에 증가하는 로직 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-16 14:38 UTC, TedJunny commented
<img width="651" alt="스크린샷 2021-09-16 오후 11 32 25" src="https://user-images.githubusercontent.com/65930935/133632200-4b1faf2b-b340-4f3e-8fec-fe1adeef03e6.png">

2021-09-17 02:40 UTC, lordmyshepherd requested changes

2021-09-17 02:40 UTC, lordmyshepherd commented on transactions/tests.py
> +from investments.models import *
`import *`은 피해주세요!
import *은 해당 모듈의 모든 class를 객체로 만들어서 메모리에 올려놓기 때문에 필요한 모듈만 import 해주세요!

```suggestion

```

2021-09-17 02:40 UTC, lordmyshepherd commented on transactions/urls.py
> +    path("/invest/<int:investment_id>", views.InvestTransactionView.as_view())
```suggestion
    path("/transaction", views.TransactionView.as_view())
```

2021-09-17 02:40 UTC, lordmyshepherd commented on transactions/urls.py
> +    path("/invest/<int:investment_id>", views.InvestTransactionView.as_view())
Transaction 관련된 endpoint는 위와 같이 transaction으로 하셔야 명확합니다!

2021-09-17 02:40 UTC, lordmyshepherd commented on transactions/views.py
> +            investment_amount = data["amounts"]
위에 URI에서 피드백 드린 것에 이어서 `investment_id`도 body에 담아서 보낼 수 있도록 구현해주세요~

2021-09-17 02:40 UTC, lordmyshepherd commented on transactions/views.py
> +            deposit = Deposit.objects.get(id=user.deposit_id)
```suggestion
            deposit = user.deposit
```

2021-09-17 02:40 UTC, lordmyshepherd commented on transactions/views.py
> +            investment = Investment.objects.get(id=investment_id)
get() 호출시 matching되는 유저가 없는 경우에 대한 에러 처리를 추가해주세요~

2021-09-17 05:04 UTC, TedJunny commented on transactions/tests.py
> +from investments.models import *
네 반여하겠습니다!

2021-09-17 05:05 UTC, TedJunny commented on transactions/urls.py
> +    path("/invest/<int:investment_id>", views.InvestTransactionView.as_view())
transaction 타입 별로 Class View를 나누고 URI에서도 어떤 거래에 대한 내용인지 명확히 해야 한다고 생각했습니다!!

2021-09-17 05:06 UTC, TedJunny commented on transactions/views.py
> +            investment_amount = data["amounts"]
이 부분은 예전에 순태 멘토님이 RESTful URI를 구현하기 위해서 Path Parameter로 쓰라고 해서 반영한 부분인데, 조금 더 의견을 나눠볼 수 있을까요?

2021-09-17 05:07 UTC, TedJunny commented on transactions/views.py
> +            investment = Investment.objects.get(id=investment_id)
로그인 데코레이터를 사용하고 있습니다! 혹시 어떤 부분에 대한 피드백인지 설명해주실 수 있을까요?

2021-09-19 05:41 UTC, TedJunny commented on transactions/views.py
> +            investment = Investment.objects.get(id=investment_id)
Investment는 user를 참조하고 있지 않습니다!

2021-09-27 01:28 UTC, lordmyshepherd requested changes

2021-09-27 01:28 UTC, lordmyshepherd commented on transactions/views.py
> +                return JsonResponse({"message": "INVALID_INPUT"}, status=400)
검증은 코드 가장 윗 단에서 하는게 효율적일 것 같네요.

2021-09-27 01:28 UTC, lordmyshepherd commented on transactions/views.py
> +            investment = Investment.objects.get(id=investment_id)
investment가 유저를 참조하고 있지 않다면, get() 호출시 matching되는 `Investment`가 없는 경우에 대한 에러 처리를 추가해주세요~

2021-09-27 02:05 UTC, TedJunny commented on transactions/views.py
> +                return JsonResponse({"message": "INVALID_INPUT"}, status=400)
수정했습니다!

2021-09-27 02:21 UTC, TedJunny commented on transactions/views.py
> +            investment = Investment.objects.get(id=investment_id)
수정했습니다!

2021-09-27 02:22 UTC, TedJunny commented on transactions/views.py
> +            investment_amount = data["amounts"]
@lordmyshepherd 이 부분에 대해서 리뷰해주실 수 있을까요?

2021-09-27 06:18 UTC, TedJunny commented on transactions/views.py
> +            investment_amount = data["amounts"]
transaction/invest/1

2021-09-27 09:28 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-27 09:28 UTC, merged