[김정수] Request merge on main from feature/jungsoo-listview
wecode-bootcamp-korea/24-2nd-111percent-backend pull request #9
Opened 2021-09-17 06:24 UTC by hollibleling

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 메인페이지 리스트 get method 기능 구현
		 
## 수정 사항들 자세한 내용
- mainpage views.py listview get method 작성
- unit tests.py 작성
- investments application의 모델링 일부 변경

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-21 08:01 UTC, TedJunny requested changes

2021-09-21 08:01 UTC, TedJunny commented on investments/urls.py
> +    ]
7 번에 라인 하나 추가해주시면 좋을 것 같습니다!

2021-09-21 08:01 UTC, TedJunny commented on investments/views.py
> +               return JsonResponse({'MESSAGE' : 'INVESTMENTS_DOES_NOT_EXISTS'}, status = 401)
Nitpick) Investment의 모델 객체의 존재여부를 판단하는 것이라면 exists()를 써서 명확하게 하는 것이 가독성에 좋을 것 같아요!

2021-09-21 08:01 UTC, TedJunny commented on investments/views.py
> +               return JsonResponse({'MESSAGE' : 'INVESTMENTS_DOES_NOT_EXISTS'}, status = 401)
10번 line return 문 indent 1칸 더 뛰워주세요!

2021-09-21 08:01 UTC, TedJunny commented on investments/views.py
> +            return JasonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
자손말고 제이슨으로 반환해주세요!

2021-09-21 08:01 UTC, TedJunny commented on investments/views.py
> +from .models import Investment, Grade, Image
Grade와 Image 모델 클래스는 선언되었지만 접근하고 있지 않습니다! 삭제해도 좋을 것 같아요

2021-09-21 08:01 UTC, TedJunny commented on investments/views.py
> +                } for investment in investments]}, status = 200)
investment 모델 객체 N개에 역참조하고 있는 image에 대하여 + 1개의 쿼리가 새로 발생할 것 같습니다!! ORM 최적화를 통해서 문제를 해결해보는 것은 어떨까요?

```suggestion
            investments = Investment.objects.prefetch_related("image_set").all()

            return JsonResponse({"investments" : [
                {
                    "id"               : investment.id,
                    "name"             : investment.name,
                    "return_rate"      : investment.return_rate,
                    "duration"         : investment.duration,
                    "target_amount"    : investment.target_amount,
                    "grade"            : investment.grade.name,
                    "image"            : investment.image_set.all().first().url,
                    "recrutement_rate" : int(investment.current_amount/investment.target_amount*100)
                } for investment in investments]}, status = 200)
```

2021-09-24 05:55 UTC, hollibleling commented on investments/urls.py
> +    ]
추가 하였습니다.

2021-09-24 05:55 UTC, hollibleling commented on investments/views.py
> +               return JsonResponse({'MESSAGE' : 'INVESTMENTS_DOES_NOT_EXISTS'}, status = 401)
변경 하였습니다~!

2021-09-24 05:55 UTC, hollibleling commented on investments/views.py
> +            return JasonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
변경하였습니다.

2021-09-24 05:55 UTC, hollibleling commented on investments/views.py
> +from .models import Investment, Grade, Image
확인 후 변경 하였습니다.

2021-09-24 05:56 UTC, hollibleling commented on investments/views.py
> +                } for investment in investments]}, status = 200)
확인 후 조언 주신대로 변경 하였습니다!!! 감사합니다.

2021-09-27 00:46 UTC, TedJunny commented
@hollibleling 커밋 1개로 요약해주세요!

2021-09-27 01:34 UTC, lordmyshepherd requested changes

2021-09-27 01:34 UTC, lordmyshepherd commented on investments/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
key error가 날 수 있는 상황이 있나요?

2021-09-27 01:34 UTC, lordmyshepherd commented on investments/views.py
> +                return JsonResponse({'MESSAGE' : 'INVESTMENTS_DOES_NOT_EXISTS'}, status = 401)
존재하지 않는 경우에 status code는 `404`입니다~

2021-09-27 02:13 UTC, hollibleling commented on investments/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
프론트쪽에서 데이터 요청할 때 key 값을 잘못 요청하였을 때를 대비하여 키에러를 따로 잡아주었습니다.

2021-09-27 02:16 UTC, hollibleling commented on investments/views.py
> +                return JsonResponse({'MESSAGE' : 'INVESTMENTS_DOES_NOT_EXISTS'}, status = 401)
확인 감사합니다. 수정 완료 하였습니다.

2021-09-27 09:30 UTC, lordmyshepherd requested changes

2021-09-27 09:30 UTC, lordmyshepherd commented on investments/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
네 error는 잡아 주셨지만 코드에서 Key Error가 날 수 있는 코드가 없습니다!

2021-09-27 09:30 UTC, lordmyshepherd commented on investments/views.py
> +            return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
불필요한 try: except문은 지워주세요~

2021-09-28 01:21 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-28 01:21 UTC, merged